baseURL = 'https://reginaldsourn.github.io/'
languageCode = 'en-us'
title = 'Rithy Sourn'

[params]
  name = "Rithy Sourn"
  tagline = "IoT Developer & Specialist"
  description = "Specializing in low-power hardware, LORA, Wi-Fi, 4G, and Wi-Fi HaLow deployments. Building hardware-software solutions from Phnom Penh, Cambodia."
  email = "sourn.rithy@gmail.com"
  location = "Phnom Penh, Cambodia"
  github = "https://github.com/reginaldsourn"
  linkedin = "https://www.linkedin.com/in/sourn-rithy-013172a8"

[markup]
  [markup.highlight]
    style = "monokai"
    noClasses = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'